/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/0K41opT8LRT
 */
import { Button } from "@/components/ui/button"
import { TableHead, TableRow, TableHeader, TableCell, TableBody, Table } from "@/components/ui/table"
import { Board } from "@/types"

interface BoardListProps{
  boards: Board[];
}

export function MojipaUnder({ boards }: BoardListProps) {
  return (
    <div className="bg-black text-white p-8">
      <h1 className="text-2xl font-bold mb-6">募集伝言板</h1>
      <div className="flex justify-between items-center mb-4">
        <div className="flex space-x-1">
          <Button className="bg-blue-500 text-white px-4 py-2 rounded">1</Button>
        </div>
      </div>
      <Table>
        <TableHeader>
          <TableRow>
            <TableHead className="w-[50px]">No</TableHead>
            <TableHead className="w-[100px]">投稿日</TableHead>
            <TableHead className="w-[150px]">ID</TableHead>
            <TableHead>コメント</TableHead>
          </TableRow>
        </TableHeader>
        <TableBody>
          {boards.map((board) => (
            <TableRow key={board.No}>
            <TableCell className="font-medium">{board.No}</TableCell>
            <TableCell>{board.Date}</TableCell>
            <TableCell>{board.Id}</TableCell>
            <TableCell>{board.Comment}
              <div className="text-blue-400">DiscordID : {board.DiscordId}</div>
            </TableCell>
            </TableRow>
          ))}
        </TableBody>
      </Table>
    </div>
  )
}
