/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/IbVIrwUXTH6
 */
import { SelectValue, SelectTrigger, SelectItem, SelectContent, Select } from "@/components/ui/select"
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"
import { Button } from "@/components/ui/button"

export function MojipaTop() {
  return (
    <div className="mx-auto p-6 bg-black text-black">
      <form>
        <div className="grid gap-6">
          <div>
            <label className="block mb-2 text-sm font-medium text-white" htmlFor="platform">
              機種
            </label>
            <Select>
              <SelectTrigger id="platform">
                <SelectValue placeholder="PC" />
              </SelectTrigger>
              <SelectContent position="popper">
                <SelectItem value="pc">PC</SelectItem>
              </SelectContent>
            </Select>
          </div>
          <div>
            <label className="block mb-2 text-sm font-medium text-white" htmlFor="region">
              目的
            </label>
            <Select>
              <SelectTrigger id="region">
                <SelectValue placeholder="フレンド" />
              </SelectTrigger>
              <SelectContent position="popper">
                <SelectItem value="friend">フレンド</SelectItem>
                <SelectItem value="multiplay">協力プレイ</SelectItem>
              </SelectContent>
            </Select>
          </div>
          <div>
            <label className="block mb-2 text-sm font-medium text-white" htmlFor="id">
              ID
            </label>
            <Input id="id" placeholder="省略可" />
            <div className="mt-1 text-xs">※表示項目を変えるとIDが非公開になります。</div>
          </div>
          <div>
            <label className="block mb-2 text-sm font-medium text-white" htmlFor="skypeId">
              SkypeID
            </label>
            <Input id="skypeId" placeholder="省略可" />
            <div className="mt-1 text-xs">※表示項目を変えるとSkypeIDが非公開になります。</div>
          </div>
          <div>
            <label className="block mb-2 text-sm font-medium text-white" htmlFor="discordId">
              DiscordID
            </label>
            <Input id="discordId" placeholder="省略可" />
            <div className="mt-1 text-xs">※表示項目を変えるとDiscordIDが非公開になります。</div>
          </div>
          <div>
            <label className="block mb-2 text-sm font-medium text-white" htmlFor="comment">
              コメント
            </label>
            <Textarea
              className="block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50"
              id="comment"
              placeholder=""
            />
          </div>
          <div>
            <Button className="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">送信</Button>
          </div>
        </div>
      </form>
      <div className="mt-6 text-xs text-white">
        ※ 管理人が管理人としてここに書き込みをする事はありませんので、管理人を名乗る者が居たとしても信用しないようにお願い致します
        <br />
        ※ ここは出会い系サイトではありません。異性との出会いを目的とした募集は禁止しています。
        <br />
        ※ 募集以外の書き込みに対しては削除＆規制する事があります。
      </div>
    </div>
  )
}
